services:
  karakal-web:
    image: ghcr.io/svenkubiak/karakal/karakal:${VERSION}
    container_name: karakal-web
    restart: always
    env_file:
      - .env
    environment:
      JAVA_OPTS: >
        -Dapplication.config=/app/config/config.yaml  
        -Xms256m
        -Xmx1024m
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config:/app/config
      - ./logs:/logs
    depends_on:
      karakal-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - karakal-network

  karakal-database:
    image: mongodb/mongodb-community-server:latest
    container_name: karakal-database
    restart: always
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
      - MONGODB_INITDB_DATABASE=${MONGODB_INITDB_DATABASE}
    volumes:
      - karakal_mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - karakal-network

networks:
  karakal-network:
    driver: bridge

volumes:
  karakal_mongodb_data: