name: Build, Dockerize, Scan

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'

jobs:
  build-docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t karakal-scan:latest .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: karakal-scan:latest
          format: table
          exit-code: '1'
          ignore-unfixed: false
          severity: LOW,MEDIUM,HIGH,CRITICAL

