name: Scan Docker Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: my-app:latest
          format: table
          output: trivy-report.txt
          exit-code: '1'            # Fail if any vulnerability is found
          ignore-unfixed: false
          severity: CRITICAL,HIGH

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

