name: Build, Dockerize, Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-app:latest .

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: my-app:latest
          format: table
          output: trivy-report.txt
          exit-code: '1'
          ignore-unfixed: false
          severity: CRITICAL,HIGH

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
